<script lang="ts">
import Check from "@lucide/svelte/icons/check";
import LinkIcon from "@lucide/svelte/icons/link";
import { toast } from "@nota/ui";
import { Badge } from "@nota/ui/shadcn/badge/index.js";
import { Button } from "@nota/ui/shadcn/button/index.js";
import * as Card from "@nota/ui/shadcn/card/index.js";
import { Separator } from "@nota/ui/shadcn/separator/index.js";
import { resolve } from "$app/paths";

let copied = $state(false);

async function copyArticleLink() {
	try {
		await navigator.clipboard.writeText(window.location.href);
		copied = true;
		toast.success("Link copied to clipboard");
		setTimeout(() => {
			copied = false;
		}, 2000);
	} catch {
		toast.error("Failed to copy link");
	}
}
</script>

<svelte:head>
  <title>Bring Your Own Key (BYOK): The Case for At-Cost AI | Nota Blog</title>
  <meta
    name="description"
    content="Why recurring $10/month AI subscription markups are unnecessary, and how connecting direct API keys provides private AI at wholesale token cost."
  />
</svelte:head>

<header class="mb-10 space-y-4">
  <div class="flex items-center gap-2 text-xs text-muted-foreground">
    <Badge variant="outline" class="text-xs">AI & Privacy</Badge>
    <span>•</span>
    <time>July 15, 2026</time>
    <span>•</span>
    <span>5 min read</span>
  </div>

  <h1 class="text-3xl sm:text-4xl font-bold tracking-tight text-foreground leading-tight">
    Bring Your Own Key (BYOK): The Case for At-Cost AI Note-Taking
  </h1>

  <p class="text-lg text-muted-foreground leading-relaxed">
    Why note apps shouldn't charge $120 a year extra for simple AI summaries, and how direct API connections keep writing private and affordable.
  </p>

  <div class="flex items-center justify-between border-y py-3 text-xs text-muted-foreground">
    <span>By Tsuzat & The Nota Team</span>
    <Button variant="ghost" size="sm" class="h-7 text-xs gap-1.5" onclick={copyArticleLink}>
      {#if copied}
        <Check class="size-3.5 text-emerald-500" />
        <span>Copied</span>
      {:else}
        <LinkIcon class="size-3.5" />
        <span>Share</span>
      {/if}
    </Button>
  </div>
</header>

<article class="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-foreground/90 leading-relaxed">
  <p>
    The integration of Large Language Models into text editors has transformed personal productivity. From generating document outlines to synthesizing meeting action items, AI assistance is quickly becoming standard. However, the commercial pricing strategy chosen by mainstream SaaS suites has created significant user frustration: the recurring AI subscription tax.
  </p>

  <h2 class="text-xl sm:text-2xl font-bold text-foreground mt-8 border-b pb-2">
    The Subscription Markup Problem
  </h2>

  <p>
    When productivity tools bundle an AI assistant, they frequently lock it behind a recurring fee—typically $10 to $15 per month on top of existing base subscriptions. When calculating the actual compute inference costs generated by typical writing sessions, an average user consumes less than $0.30 worth of API tokens over an entire month of usage.
  </p>

  <!-- Cost Comparison Cards -->
  <div class="grid gap-4 sm:grid-cols-2 my-6">
    <Card.Root class="p-5">
      <div class="text-xs text-muted-foreground font-medium">SaaS Add-on Model</div>
      <div class="text-2xl font-bold text-foreground mt-1">$120 – $180 / yr</div>
      <div class="text-xs text-muted-foreground mt-1">Fixed monthly subscription regardless of usage.</div>
    </Card.Root>

    <Card.Root class="p-5">
      <div class="text-xs text-muted-foreground font-medium">Nota BYOK Model</div>
      <div class="text-2xl font-bold text-foreground mt-1">~$3 – $5 / yr</div>
      <div class="text-xs text-muted-foreground mt-1">Pay direct provider token costs for actual usage.</div>
    </Card.Root>
  </div>

  <h2 class="text-xl sm:text-2xl font-bold text-foreground mt-8 border-b pb-2">
    The Nota BYOK Approach
  </h2>

  <p>
    Nota supports a <strong>Bring Your Own Key (BYOK)</strong> architecture. In the desktop application settings, you can securely store your personal API keys for OpenAI (GPT-4o), Anthropic (Claude 3.5), or Google (Gemini).
  </p>

  <h2 class="text-xl sm:text-2xl font-bold text-foreground mt-8 border-b pb-2">
    Key Advantages
  </h2>

  <ul class="space-y-2 list-disc pl-5">
    <li><strong>At-Cost Token Pricing:</strong> Pay exact per-token rates directly to model providers with zero intermediary markup.</li>
    <li><strong>Data Privacy:</strong> Note contents travel directly from your local secure storage to the AI provider under enterprise API privacy terms.</li>
    <li><strong>Model Choice:</strong> Switch seamlessly between Anthropic Claude for long-form drafting and OpenAI for structured transformations.</li>
  </ul>

  <p>
    For users who prefer an out-of-the-box experience without managing developer API keys, Nota Pro also includes bundled server-side credits.
  </p>
</article>

<Separator class="my-10" />

<div class="flex flex-col sm:flex-row items-center justify-between gap-4 p-6 rounded-lg border bg-muted/20">
  <div class="space-y-1 text-center sm:text-left">
    <div class="font-semibold text-foreground">Write with your own AI keys</div>
    <div class="text-xs text-muted-foreground">Available on the Nota Desktop App.</div>
  </div>
  <Button href={resolve("/#pricing")}>
    Try Nota Free
  </Button>
</div>
